title: "Giving Life Meaning "
author: "Lingbo Zhang"
description: "'Don't put off until tomorrow what you can do today.' ― benjamin franklin"

# Jekyll settings
permalink: /:title/          # see https://jekyllrb.com/docs/permalinks/
paginate: 2                  # number of articles per page, remove to disable pagination
excerpt_separator: "\n\n\n"  # indicates the end of the excerpt by two blank lines

# Theme settings
show_excerpts: false         # show article previews on the home page instead of headlines
date_format: "%B %d, %Y"     # see http://shopify.github.io/liquid/filters/date/
dark_theme: false            # enables dark mode
dark_header: false           # uses dark header whether dark_theme is enabled or not
minimal_theme: false         # radically minimalistic theme

navigation:                  # show navigation links in the header	
  - index.html	
  - archive.md	
  - about.md


icons:                       # show icons in the header, for all possible icons see http://fontawesome.io/icons/
  envelope: "mailto:lingboz2015@gmail.com"
  github: "https://github.com/lingbozhang"
  rss: "/contrast/feed.xml"

comments:                    # embed disqus or isso comments
#  disqus: "disqus-contrast"
#  isso: "comments.mysite.org"

remote_theme: niklasbuschmann/contrast

plugins: 
 - jekyll-remote-theme
 - jekyll-feed
 - jekyll-paginate
 - jekyll-default-layout
